### ISSUE TITLE
Beartype is still not an optional dependency

### ISSUE THREAD

**Issue by rk-terence** [gabrieldemarmiesse/overtake#7]
Thank you for your inspiring package!
In https://github.com/gabrieldemarmiesse/overtake/issues/2, I see that you add a `basic` type checker.
The thing is that if we use `overtake` without `beartype`, an exception will be raised:
```
ModuleNotFoundError: No module named 'beartype'
```

I think the reason is here in the code
https://github.com/gabrieldemarmiesse/overtake/blob/3a8e93c1c0816680e910b29432053610231e0ff3/src/overtake/incompatibility_reasons.py#L5C1-L6C21
`overtake` still tries to import from `beartype`.

**Comment by gabrieldemarmiesse** [comment]
You are right. This is indeed a bug. I'm open to a pull request to fix it.

**Comment by gabrieldemarmiesse** [comment]
Closing as the repository is not maintained anymore :(
